--
--  Copyright 2025 (C) Daniel King
--
--  SPDX-License-Identifier: Apache-2.0
--
with Ada.Command_Line;
with Ada.Text_IO; use Ada.Text_IO;
with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;
with Interfaces;

with LibCRC;
with LibCRC.Predefined;
with LibCRC.Predefined.RAM_Tables;
with LibCRC.Predefined.Bitwise;

with Generic_CRC_Driver;

--  This program computes the CRC over the standard input, using the CRC
--  algorithm specified as the first argument on the command line.
--
--  The names are taken from the CRC RevEng catalogue at:
--  https://reveng.sourceforge.io/crc-catalogue/

procedure Driver is

   package CRC8_Driver  is new Generic_CRC_Driver (Interfaces.Unsigned_8);
   package CRC16_Driver is new Generic_CRC_Driver (Interfaces.Unsigned_16);
   package CRC24_Driver is new Generic_CRC_Driver (LibCRC.Unsigned_24);
   package CRC32_Driver is new Generic_CRC_Driver (Interfaces.Unsigned_32);
   package CRC64_Driver is new Generic_CRC_Driver (Interfaces.Unsigned_64);

   package PROM renames LibCRC.Predefined;
   package PRAM renames LibCRC.Predefined.RAM_Tables;
   package PBit renames LibCRC.Predefined.Bitwise;

   CRC8_Table : constant CRC8_Driver.CRC_Info_Array :=
     ((Name         => To_Unbounded_String ("CRC-8/AUTOSAR"),
       ROM_Func     => PROM.CRC_8_AUTOSAR.Calculate'Access,
       RAM_Func     => PRAM.CRC_8_AUTOSAR.Calculate'Access,
       Bitwise_Func => PBit.CRC_8_AUTOSAR.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-8/BLUETOOTH"),
       ROM_Func     => PROM.CRC_8_BLUETOOTH.Calculate'Access,
       RAM_Func     => PRAM.CRC_8_BLUETOOTH.Calculate'Access,
       Bitwise_Func => PBit.CRC_8_BLUETOOTH.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-8/DARC"),
       ROM_Func     => PROM.CRC_8_DARC.Calculate'Access,
       RAM_Func     => PRAM.CRC_8_DARC.Calculate'Access,
       Bitwise_Func => PBit.CRC_8_DARC.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-8/HITAG"),
       ROM_Func     => PROM.CRC_8_HITAG.Calculate'Access,
       RAM_Func     => PRAM.CRC_8_HITAG.Calculate'Access,
       Bitwise_Func => PBit.CRC_8_HITAG.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-8/I-CODE"),
       ROM_Func     => PROM.CRC_8_I_CODE.Calculate'Access,
       RAM_Func     => PRAM.CRC_8_I_CODE.Calculate'Access,
       Bitwise_Func => PBit.CRC_8_I_CODE.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-8/MAXIM-DOW"),
       ROM_Func     => PROM.CRC_8_MAXIM_DOW.Calculate'Access,
       RAM_Func     => PRAM.CRC_8_MAXIM_DOW.Calculate'Access,
       Bitwise_Func => PBit.CRC_8_MAXIM_DOW.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-8/MAXIM"),
       ROM_Func     => PROM.CRC_8_MAXIM.Calculate'Access,
       RAM_Func     => PRAM.CRC_8_MAXIM.Calculate'Access,
       Bitwise_Func => PBit.CRC_8_MAXIM.Calculate'Access),
      (Name         => To_Unbounded_String ("DOW-CRC"),
       ROM_Func     => PROM.DOW_CRC.Calculate'Access,
       RAM_Func     => PRAM.DOW_CRC.Calculate'Access,
       Bitwise_Func => PBit.DOW_CRC.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-8/MIFARE-MAD"),
       ROM_Func     => PROM.CRC_8_MIFARE_MAD.Calculate'Access,
       RAM_Func     => PRAM.CRC_8_MIFARE_MAD.Calculate'Access,
       Bitwise_Func => PBit.CRC_8_MIFARE_MAD.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-8/NRSC-5"),
       ROM_Func     => PROM.CRC_8_NRSC_5.Calculate'Access,
       RAM_Func     => PRAM.CRC_8_NRSC_5.Calculate'Access,
       Bitwise_Func => PBit.CRC_8_NRSC_5.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-8/OPENSAFETY"),
       ROM_Func     => PROM.CRC_8_OPENSAFETY.Calculate'Access,
       RAM_Func     => PRAM.CRC_8_OPENSAFETY.Calculate'Access,
       Bitwise_Func => PBit.CRC_8_OPENSAFETY.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-8/SAE-J1850"),
       ROM_Func     => PROM.CRC_8_SAE_J1850.Calculate'Access,
       RAM_Func     => PRAM.CRC_8_SAE_J1850.Calculate'Access,
       Bitwise_Func => PBit.CRC_8_SAE_J1850.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-8/SMBUS"),
       ROM_Func     => PROM.CRC_8_SMBUS.Calculate'Access,
       RAM_Func     => PRAM.CRC_8_SMBUS.Calculate'Access,
       Bitwise_Func => PBit.CRC_8_SMBUS.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-8"),
       ROM_Func     => PROM.CRC_8.Calculate'Access,
       RAM_Func     => PRAM.CRC_8.Calculate'Access,
       Bitwise_Func => PBit.CRC_8.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-8/TECH-3250"),
       ROM_Func     => PROM.CRC_8_TECH_3250.Calculate'Access,
       RAM_Func     => PRAM.CRC_8_TECH_3250.Calculate'Access,
       Bitwise_Func => PBit.CRC_8_TECH_3250.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-8/AES"),
       ROM_Func     => PROM.CRC_8_AES.Calculate'Access,
       RAM_Func     => PRAM.CRC_8_AES.Calculate'Access,
       Bitwise_Func => PBit.CRC_8_AES.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-8/EBU"),
       ROM_Func     => PROM.CRC_8_EBU.Calculate'Access,
       RAM_Func     => PRAM.CRC_8_EBU.Calculate'Access,
       Bitwise_Func => PBit.CRC_8_EBU.Calculate'Access));

   CRC16_Table : constant CRC16_Driver.CRC_Info_Array :=
     ((Name         => To_Unbounded_String ("CRC-16/ARC"),
       ROM_Func     => PROM.CRC_16_ARC.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_ARC.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_ARC.Calculate'Access),
      (Name         => To_Unbounded_String ("ARC"),
       ROM_Func     => PROM.ARC.Calculate'Access,
       RAM_Func     => PRAM.ARC.Calculate'Access,
       Bitwise_Func => PBit.ARC.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16"),
       ROM_Func     => PROM.CRC_16.Calculate'Access,
       RAM_Func     => PRAM.CRC_16.Calculate'Access,
       Bitwise_Func => PBit.CRC_16.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/LHA"),
       ROM_Func     => PROM.CRC_16_LHA.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_LHA.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_LHA.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/IBM"),
       ROM_Func     => PROM.CRC_16_IBM.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_IBM.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_IBM.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/DDS-110"),
       ROM_Func     => PROM.CRC_16_DDS_110.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_DDS_110.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_DDS_110.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/DECT-R"),
       ROM_Func     => PROM.CRC_16_DECT_R.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_DECT_R.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_DECT_R.Calculate'Access),
      (Name         => To_Unbounded_String ("R-CRC-16"),
       ROM_Func     => PROM.R_CRC_16.Calculate'Access,
       RAM_Func     => PRAM.R_CRC_16.Calculate'Access,
       Bitwise_Func => PBit.R_CRC_16.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/DECT-X"),
       ROM_Func     => PROM.CRC_16_DECT_X.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_DECT_X.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_DECT_X.Calculate'Access),
      (Name         => To_Unbounded_String ("X-CRC-16"),
       ROM_Func     => PROM.X_CRC_16.Calculate'Access,
       RAM_Func     => PRAM.X_CRC_16.Calculate'Access,
       Bitwise_Func => PBit.X_CRC_16.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/DNP"),
       ROM_Func     => PROM.CRC_16_DNP.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_DNP.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_DNP.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/EN-13757"),
       ROM_Func     => PROM.CRC_16_EN_13757.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_EN_13757.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_EN_13757.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/GENIBUS"),
       ROM_Func     => PROM.CRC_16_GENIBUS.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_GENIBUS.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_GENIBUS.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/DARC"),
       ROM_Func     => PROM.CRC_16_DARC.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_DARC.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_DARC.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/EPC"),
       ROM_Func     => PROM.CRC_16_EPC.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_EPC.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_EPC.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/EPC-C1G2"),
       ROM_Func     => PROM.CRC_16_EPC_C1G2.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_EPC_C1G2.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_EPC_C1G2.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/I-CODE"),
       ROM_Func     => PROM.CRC_16_I_CODE.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_I_CODE.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_I_CODE.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/GSM"),
       ROM_Func     => PROM.CRC_16_GSM.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_GSM.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_GSM.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/IBM-3740"),
       ROM_Func     => PROM.CRC_16_IBM_3740.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_IBM_3740.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_IBM_3740.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/AUTOSAR"),
       ROM_Func     => PROM.CRC_16_AUTOSAR.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_AUTOSAR.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_AUTOSAR.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/CCITT-FALSE"),
       ROM_Func     => PROM.CRC_16_CCITT_FALSE.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_CCITT_FALSE.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_CCITT_FALSE.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/IBM-SDLC"),
       ROM_Func     => PROM.CRC_16_IBM_SDLC.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_IBM_SDLC.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_IBM_SDLC.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/ISO-HDLC"),
       ROM_Func     => PROM.CRC_16_ISO_HDLC.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_ISO_HDLC.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_ISO_HDLC.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/ISO-IEC-14443-3-B"),
       ROM_Func     => PROM.CRC_16_ISO_IEC_14443_3_B.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_ISO_IEC_14443_3_B.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_ISO_IEC_14443_3_B.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/X-25"),
       ROM_Func     => PROM.CRC_16_X_25.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_X_25.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_X_25.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-B"),
       ROM_Func     => PROM.CRC_B.Calculate'Access,
       RAM_Func     => PRAM.CRC_B.Calculate'Access,
       Bitwise_Func => PBit.CRC_B.Calculate'Access),
      (Name         => To_Unbounded_String ("X-25"),
       ROM_Func     => PROM.X_25.Calculate'Access,
       RAM_Func     => PRAM.X_25.Calculate'Access,
       Bitwise_Func => PBit.X_25.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/ISO-IEC-14443-3-A"),
       ROM_Func     => PROM.CRC_16_ISO_IEC_14443_3_A.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_ISO_IEC_14443_3_A.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_ISO_IEC_14443_3_A.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-A"),
       ROM_Func     => PROM.CRC_A.Calculate'Access,
       RAM_Func     => PRAM.CRC_A.Calculate'Access,
       Bitwise_Func => PBit.CRC_A.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/KERMIT"),
       ROM_Func     => PROM.CRC_16_KERMIT.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_KERMIT.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_KERMIT.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/BLUETOOTH"),
       ROM_Func     => PROM.CRC_16_BLUETOOTH.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_BLUETOOTH.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_BLUETOOTH.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/CCITT"),
       ROM_Func     => PROM.CRC_16_CCITT.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_CCITT.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_CCITT.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/CCITT-TRUE"),
       ROM_Func     => PROM.CRC_16_CCITT_TRUE.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_CCITT_TRUE.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_CCITT_TRUE.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/V-41-LSB"),
       ROM_Func     => PROM.CRC_16_V_41_LSB.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_V_41_LSB.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_V_41_LSB.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-CCITT"),
       ROM_Func     => PROM.CRC_CCITT.Calculate'Access,
       RAM_Func     => PRAM.CRC_CCITT.Calculate'Access,
       Bitwise_Func => PBit.CRC_CCITT.Calculate'Access),
      (Name         => To_Unbounded_String ("KERMIT"),
       ROM_Func     => PROM.KERMIT.Calculate'Access,
       RAM_Func     => PRAM.KERMIT.Calculate'Access,
       Bitwise_Func => PBit.KERMIT.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/M17"),
       ROM_Func     => PROM.CRC_16_M17.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_M17.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_M17.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/MAXIM-DOW"),
       ROM_Func     => PROM.CRC_16_MAXIM_DOW.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_MAXIM_DOW.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_MAXIM_DOW.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/MAXIM"),
       ROM_Func     => PROM.CRC_16_MAXIM.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_MAXIM.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_MAXIM.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/MCRF4XX"),
       ROM_Func     => PROM.CRC_16_MCRF4XX.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_MCRF4XX.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_MCRF4XX.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/MODBUS"),
       ROM_Func     => PROM.CRC_16_MODBUS.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_MODBUS.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_MODBUS.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/NRSC-5"),
       ROM_Func     => PROM.CRC_16_NRSC_5.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_NRSC_5.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_NRSC_5.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/OPENSAFETY-A"),
       ROM_Func     => PROM.CRC_16_OPENSAFETY_A.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_OPENSAFETY_A.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_OPENSAFETY_A.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/OPENSAFETY-B"),
       ROM_Func     => PROM.CRC_16_OPENSAFETY_B.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_OPENSAFETY_B.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_OPENSAFETY_B.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/PROFIBUS"),
       ROM_Func     => PROM.CRC_16_PROFIBUS.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_PROFIBUS.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_PROFIBUS.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/IEC-61158-2"),
       ROM_Func     => PROM.CRC_16_IEC_61158_2.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_IEC_61158_2.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_IEC_61158_2.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/SPI_FUJITSU"),
       ROM_Func     => PROM.CRC_16_SPI_FUJITSU.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_SPI_FUJITSU.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_SPI_FUJITSU.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/AUG-CCITT"),
       ROM_Func     => PROM.CRC_16_AUG_CCITT.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_AUG_CCITT.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_AUG_CCITT.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/T10-DIF"),
       ROM_Func     => PROM.CRC_16_T10_DIF.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_T10_DIF.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_T10_DIF.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/TELEDISK"),
       ROM_Func     => PROM.CRC_16_TELEDISK.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_TELEDISK.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_TELEDISK.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/TMS37157"),
       ROM_Func     => PROM.CRC_16_TMS37157.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_TMS37157.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_TMS37157.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/UMTS"),
       ROM_Func     => PROM.CRC_16_UMTS.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_UMTS.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_UMTS.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/BUYPASS"),
       ROM_Func     => PROM.CRC_16_BUYPASS.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_BUYPASS.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_BUYPASS.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/VERIFONE"),
       ROM_Func     => PROM.CRC_16_VERIFONE.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_VERIFONE.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_VERIFONE.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/USB"),
       ROM_Func     => PROM.CRC_16_USB.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_USB.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_USB.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/XMODEM"),
       ROM_Func     => PROM.CRC_16_XMODEM.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_XMODEM.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_XMODEM.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/ACORN"),
       ROM_Func     => PROM.CRC_16_ACORN.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_ACORN.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_ACORN.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/LTE"),
       ROM_Func     => PROM.CRC_16_LTE.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_LTE.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_LTE.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-16/V-41-MSB"),
       ROM_Func     => PROM.CRC_16_V_41_MSB.Calculate'Access,
       RAM_Func     => PRAM.CRC_16_V_41_MSB.Calculate'Access,
       Bitwise_Func => PBit.CRC_16_V_41_MSB.Calculate'Access),
      (Name         => To_Unbounded_String ("XMODEM"),
       ROM_Func     => PROM.XMODEM.Calculate'Access,
       RAM_Func     => PRAM.XMODEM.Calculate'Access,
       Bitwise_Func => PBit.XMODEM.Calculate'Access),
      (Name         => To_Unbounded_String ("ZMODEM"),
       ROM_Func     => PROM.ZMODEM.Calculate'Access,
       RAM_Func     => PRAM.ZMODEM.Calculate'Access,
       Bitwise_Func => PBit.ZMODEM.Calculate'Access));

   CRC24_Table : constant CRC24_Driver.CRC_Info_Array :=
     ((Name         => To_Unbounded_String ("CRC-24/BLE"),
       ROM_Func     => PROM.CRC_24_BLE.Calculate'Access,
       RAM_Func     => PRAM.CRC_24_BLE.Calculate'Access,
       Bitwise_Func => PBit.CRC_24_BLE.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-24/FLEXRAY-A"),
       ROM_Func     => PROM.CRC_24_FLEXRAY_A.Calculate'Access,
       RAM_Func     => PRAM.CRC_24_FLEXRAY_A.Calculate'Access,
       Bitwise_Func => PBit.CRC_24_FLEXRAY_A.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-24/FLEXRAY-B"),
       ROM_Func     => PROM.CRC_24_FLEXRAY_B.Calculate'Access,
       RAM_Func     => PRAM.CRC_24_FLEXRAY_B.Calculate'Access,
       Bitwise_Func => PBit.CRC_24_FLEXRAY_B.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-24/OPENPGP"),
       ROM_Func     => PROM.CRC_24_OPENPGP.Calculate'Access,
       RAM_Func     => PRAM.CRC_24_OPENPGP.Calculate'Access,
       Bitwise_Func => PBit.CRC_24_OPENPGP.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-24"),
       ROM_Func     => PROM.CRC_24.Calculate'Access,
       RAM_Func     => PRAM.CRC_24.Calculate'Access,
       Bitwise_Func => PBit.CRC_24.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-24/OS-9"),
       ROM_Func     => PROM.CRC_24_OS_9.Calculate'Access,
       RAM_Func     => PRAM.CRC_24_OS_9.Calculate'Access,
       Bitwise_Func => PBit.CRC_24_OS_9.Calculate'Access));

   CRC32_Table : constant CRC32_Driver.CRC_Info_Array :=
     ((Name         => To_Unbounded_String ("CRC-32/AIXM"),
       ROM_Func     => PROM.CRC_32_AIXM.Calculate'Access,
       RAM_Func     => PRAM.CRC_32_AIXM.Calculate'Access,
       Bitwise_Func => PBit.CRC_32_AIXM.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-32Q"),
       ROM_Func     => PROM.CRC_32Q.Calculate'Access,
       RAM_Func     => PRAM.CRC_32Q.Calculate'Access,
       Bitwise_Func => PBit.CRC_32Q.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-32/AUTOSAR"),
       ROM_Func     => PROM.CRC_32_AUTOSAR.Calculate'Access,
       RAM_Func     => PRAM.CRC_32_AUTOSAR.Calculate'Access,
       Bitwise_Func => PBit.CRC_32_AUTOSAR.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-32/BASE91-D"),
       ROM_Func     => PROM.CRC_32_BASE91_D.Calculate'Access,
       RAM_Func     => PRAM.CRC_32_BASE91_D.Calculate'Access,
       Bitwise_Func => PBit.CRC_32_BASE91_D.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-32D"),
       ROM_Func     => PROM.CRC_32D.Calculate'Access,
       RAM_Func     => PRAM.CRC_32D.Calculate'Access,
       Bitwise_Func => PBit.CRC_32D.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-32/BZIP2"),
       ROM_Func     => PROM.CRC_32_BZIP2.Calculate'Access,
       RAM_Func     => PRAM.CRC_32_BZIP2.Calculate'Access,
       Bitwise_Func => PBit.CRC_32_BZIP2.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-32/AAL5"),
       ROM_Func     => PROM.CRC_32_AAL5.Calculate'Access,
       RAM_Func     => PRAM.CRC_32_AAL5.Calculate'Access,
       Bitwise_Func => PBit.CRC_32_AAL5.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-32/DECT_B"),
       ROM_Func     => PROM.CRC_32_DECT_B.Calculate'Access,
       RAM_Func     => PRAM.CRC_32_DECT_B.Calculate'Access,
       Bitwise_Func => PBit.CRC_32_DECT_B.Calculate'Access),
      (Name         => To_Unbounded_String ("B-CRC-32"),
       ROM_Func     => PROM.B_CRC_32.Calculate'Access,
       RAM_Func     => PRAM.B_CRC_32.Calculate'Access,
       Bitwise_Func => PBit.B_CRC_32.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-32/CKSUM"),
       ROM_Func     => PROM.CRC_32_CKSUM.Calculate'Access,
       RAM_Func     => PRAM.CRC_32_CKSUM.Calculate'Access,
       Bitwise_Func => PBit.CRC_32_CKSUM.Calculate'Access),
      (Name         => To_Unbounded_String ("CKSUM"),
       ROM_Func     => PROM.CKSUM.Calculate'Access,
       RAM_Func     => PRAM.CKSUM.Calculate'Access,
       Bitwise_Func => PBit.CKSUM.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-32/POSIX"),
       ROM_Func     => PROM.CRC_32_POSIX.Calculate'Access,
       RAM_Func     => PRAM.CRC_32_POSIX.Calculate'Access,
       Bitwise_Func => PBit.CRC_32_POSIX.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-32/ISCSI"),
       ROM_Func     => PROM.CRC_32_ISCSI.Calculate'Access,
       RAM_Func     => PRAM.CRC_32_ISCSI.Calculate'Access,
       Bitwise_Func => PBit.CRC_32_ISCSI.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-32/BASE91-C"),
       ROM_Func     => PROM.CRC_32_BASE91_C.Calculate'Access,
       RAM_Func     => PRAM.CRC_32_BASE91_C.Calculate'Access,
       Bitwise_Func => PBit.CRC_32_BASE91_C.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-32/CASTAGNOLI"),
       ROM_Func     => PROM.CRC_32_CASTAGNOLI.Calculate'Access,
       RAM_Func     => PRAM.CRC_32_CASTAGNOLI.Calculate'Access,
       Bitwise_Func => PBit.CRC_32_CASTAGNOLI.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-32/INTERLAKEN"),
       ROM_Func     => PROM.CRC_32_INTERLAKEN.Calculate'Access,
       RAM_Func     => PRAM.CRC_32_INTERLAKEN.Calculate'Access,
       Bitwise_Func => PBit.CRC_32_INTERLAKEN.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-32C"),
       ROM_Func     => PROM.CRC_32C.Calculate'Access,
       RAM_Func     => PRAM.CRC_32C.Calculate'Access,
       Bitwise_Func => PBit.CRC_32C.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-32/NVME"),
       ROM_Func     => PROM.CRC_32_NVME.Calculate'Access,
       RAM_Func     => PRAM.CRC_32_NVME.Calculate'Access,
       Bitwise_Func => PBit.CRC_32_NVME.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-32/ISO-HDLC"),
       ROM_Func     => PROM.CRC_32_ISO_HDLC.Calculate'Access,
       RAM_Func     => PRAM.CRC_32_ISO_HDLC.Calculate'Access,
       Bitwise_Func => PBit.CRC_32_ISO_HDLC.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-32"),
       ROM_Func     => PROM.CRC_32.Calculate'Access,
       RAM_Func     => PRAM.CRC_32.Calculate'Access,
       Bitwise_Func => PBit.CRC_32.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-32/ADCCP"),
       ROM_Func     => PROM.CRC_32_ADCCP.Calculate'Access,
       RAM_Func     => PRAM.CRC_32_ADCCP.Calculate'Access,
       Bitwise_Func => PBit.CRC_32_ADCCP.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-32/V-42"),
       ROM_Func     => PROM.CRC_32_V_42.Calculate'Access,
       RAM_Func     => PRAM.CRC_32_V_42.Calculate'Access,
       Bitwise_Func => PBit.CRC_32_V_42.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-32/XZ"),
       ROM_Func     => PROM.CRC_32_XZ.Calculate'Access,
       RAM_Func     => PRAM.CRC_32_XZ.Calculate'Access,
       Bitwise_Func => PBit.CRC_32_XZ.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-32/JAMCRC"),
       ROM_Func     => PROM.CRC_32_JAMCRC.Calculate'Access,
       RAM_Func     => PRAM.CRC_32_JAMCRC.Calculate'Access,
       Bitwise_Func => PBit.CRC_32_JAMCRC.Calculate'Access),
      (Name         => To_Unbounded_String ("JAMCRC"),
       ROM_Func     => PROM.JAMCRC.Calculate'Access,
       RAM_Func     => PRAM.JAMCRC.Calculate'Access,
       Bitwise_Func => PBit.JAMCRC.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-32/MEF"),
       ROM_Func     => PROM.CRC_32_MEF.Calculate'Access,
       RAM_Func     => PRAM.CRC_32_MEF.Calculate'Access,
       Bitwise_Func => PBit.CRC_32_MEF.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-32/MPEG-2"),
       ROM_Func     => PROM.CRC_32_MPEG_2.Calculate'Access,
       RAM_Func     => PRAM.CRC_32_MPEG_2.Calculate'Access,
       Bitwise_Func => PBit.CRC_32_MPEG_2.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-32/XFER"),
       ROM_Func     => PROM.CRC_32_XFER.Calculate'Access,
       RAM_Func     => PRAM.CRC_32_XFER.Calculate'Access,
       Bitwise_Func => PBit.CRC_32_XFER.Calculate'Access));

   CRC64_Table : constant CRC64_Driver.CRC_Info_Array :=
     ((Name         => To_Unbounded_String ("CRC-64/ECMA-182"),
       ROM_Func     => PROM.CRC_64_ECMA_182.Calculate'Access,
       RAM_Func     => PRAM.CRC_64_ECMA_182.Calculate'Access,
       Bitwise_Func => PBit.CRC_64_ECMA_182.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-64"),
       ROM_Func     => PROM.CRC_64.Calculate'Access,
       RAM_Func     => PRAM.CRC_64.Calculate'Access,
       Bitwise_Func => PBit.CRC_64.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-64/GO-ISO"),
       ROM_Func     => PROM.CRC_64_GO_ISO.Calculate'Access,
       RAM_Func     => PRAM.CRC_64_GO_ISO.Calculate'Access,
       Bitwise_Func => PBit.CRC_64_GO_ISO.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-64/MS"),
       ROM_Func     => PROM.CRC_64_MS.Calculate'Access,
       RAM_Func     => PRAM.CRC_64_MS.Calculate'Access,
       Bitwise_Func => PBit.CRC_64_MS.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-64/NVME"),
       ROM_Func     => PROM.CRC_64_NVME.Calculate'Access,
       RAM_Func     => PRAM.CRC_64_NVME.Calculate'Access,
       Bitwise_Func => PBit.CRC_64_NVME.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-64/WE"),
       ROM_Func     => PROM.CRC_64_WE.Calculate'Access,
       RAM_Func     => PRAM.CRC_64_WE.Calculate'Access,
       Bitwise_Func => PBit.CRC_64_WE.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-64/XZ"),
       ROM_Func     => PROM.CRC_64_XZ.Calculate'Access,
       RAM_Func     => PRAM.CRC_64_XZ.Calculate'Access,
       Bitwise_Func => PBit.CRC_64_XZ.Calculate'Access),
      (Name         => To_Unbounded_String ("CRC-64/GO-ECMA"),
       ROM_Func     => PROM.CRC_64_GO_ECMA.Calculate'Access,
       RAM_Func     => PRAM.CRC_64_GO_ECMA.Calculate'Access,
       Bitwise_Func => PBit.CRC_64_GO_ECMA.Calculate'Access));

begin
   if Ada.Command_Line.Argument_Count /= 1 then
      Put_Line (Standard_Error, "usage: driver <algo-name>");
      Ada.Command_Line.Set_Exit_Status (1);
      return;
   end if;

   declare
      Name : constant String := Ada.Command_Line.Argument (1);
   begin
      for Info of CRC8_Table loop
         if Name = Info.Name then
            CRC8_Driver.Process_Stdin (Info);
            return;
         end if;
      end loop;

      for Info of CRC16_Table loop
         if Name = Info.Name then
            CRC16_Driver.Process_Stdin (Info);
            return;
         end if;
      end loop;

      for Info of CRC24_Table loop
         if Name = Info.Name then
            CRC24_Driver.Process_Stdin (Info);
            return;
         end if;
      end loop;

      for Info of CRC32_Table loop
         if Name = Info.Name then
            CRC32_Driver.Process_Stdin (Info);
            return;
         end if;
      end loop;

      for Info of CRC64_Table loop
         if Name = Info.Name then
            CRC64_Driver.Process_Stdin (Info);
            return;
         end if;
      end loop;

      Put (Standard_Error, "Unknown CRC: ");
      Put_Line (Standard_Error, Name);
      Ada.Command_Line.Set_Exit_Status (1);
   end;
end Driver;
