name = "libcrc"
description = "Cyclic Redundancy Check (CRC) Library"
version = "1.1.0-dev"

authors = ["Daniel King"]
maintainers = ["Daniel King <damaki.gh@gmail.com>"]
maintainers-logins = ["damaki"]
licenses = "Apache-2.0"
website = "https://github.com/damaki/libcrc"
tags = ["crc", "crc32", "spark", "error-checking"]
