name = "proof"
description = "Dummy crate with GNATprove dependency for proving libcrc"
version = "0.1.0-dev"

authors = ["Daniel King"]
maintainers = ["Daniel King <damaki.gh@gmail.com>"]
maintainers-logins = ["damaki"]
licenses = "Apache-2.0"
website = ""
tags = []

[[depends-on]]
gnatprove = "^15.1.0"
